# 跟随 Andrej Karpathy 学习 Neural Networks: Zero to Hero 的笔记

In [14]:
words = open('./data/中文成语集.txt', 'r').read().splitlines()

In [15]:
words[:10]

['\ufeff前所未有',
 '毫无疑问',
 '无论如何',
 '不可思议',
 '不可避免',
 '脱颖而出',
 '莫名其妙',
 '不知不觉',
 '众所周知',
 '有感而发']

In [16]:
len(words)

50373

In [17]:
min(len(w) for w in words)

4

In [18]:
max(len(w) for w in words)

8

In [24]:
b = {}
for w in words[:1]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1
        print(bigram)



('<S>', '\ufeff')
('\ufeff', '前')
('前', '所')
('所', '未')
('未', '有')
('有', '<E>')


In [22]:
sorted(b.items(), key= lambda kv: -kv[1])


[(('<S>', '一'), 919),
 (('<S>', '不'), 878),
 (('<S>', '无'), 459),
 (('人', '<E>'), 452),
 (('<S>', '大'), 432),
 (('<S>', '人'), 399),
 (('<S>', '三'), 361),
 (('心', '<E>'), 336),
 (('<S>', '风'), 323),
 (('地', '<E>'), 319),
 (('<S>', '天'), 291),
 (('<S>', '以'), 280),
 (('<S>', '有'), 278),
 (('<S>', '百'), 277),
 (('<S>', '心'), 271),
 (('<S>', '千'), 250),
 (('行', '<E>'), 247),
 (('子', '<E>'), 240),
 (('下', '<E>'), 239),
 (('<S>', '东'), 238),
 (('言', '<E>'), 230),
 (('天', '<E>'), 230),
 (('<S>', '高'), 220),
 (('生', '<E>'), 217),
 (('事', '<E>'), 217),
 (('气', '<E>'), 202),
 (('<S>', '如'), 201),
 (('意', '<E>'), 199),
 (('<S>', '金'), 198),
 (('风', '<E>'), 192),
 (('道', '<E>'), 189),
 (('水', '<E>'), 188),
 (('不', '可'), 182),
 (('<S>', '自'), 179),
 (('<S>', '神'), 179),
 (('<S>', '日'), 176),
 (('雨', '<E>'), 174),
 (('语', '<E>'), 171),
 (('马', '<E>'), 171),
 (('山', '<E>'), 169),
 (('日', '<E>'), 164),
 (('<S>', '出'), 161),
 (('<S>', '白'), 160),
 (('来', '<E>'), 157),
 (('目', '<E>'), 156),
 (('之', '<E>

In [9]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
N = torch.zeros((2272, 2272), dtype=torch.int32)


In [11]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [12]:

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1


In [13]:
# plt.figure(figsize=(16, 16))
# plt.imshow(N, cmap='Blues')
# for i in range(2272):
#     for j in range(2272):
#         chstr = itos[i] + itos[j]
#         plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
#         plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
# plt.axis('off')

In [14]:
N[0, :].shape

torch.Size([2272])

In [15]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000e+00, 0.0000e+00, 5.2026e-03,  ..., 2.3003e-03, 2.5449e-03,
        8.7365e-07])

In [16]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'华'

In [17]:
# test 1
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [18]:
# test 2
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [19]:
p.shape

torch.Size([3])

In [20]:
P.shape

NameError: name 'P' is not defined

In [ ]:
P.sum(1)

tensor([1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000])

In [ ]:
# 2272 x 2272
# 2272 x 1

In [21]:
P = N.float()
P /= P.sum(1, keepdim=True)

In [22]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
    out = []
    ix = 0

    while True:
        # p = N[ix].float()
        # p = p / p.sum()
        # p = torch.ones(2272) / 2272
        p = P[ix]

        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

华.
张全庸.
林增源.
杨永策.
高宝.


In [ ]:
# log(a*b*c) = log(a) + log(b) + log(c)

In [25]:
log_likelihood = 0.0
n = 0

for w in words[:10]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob

        n += 1

        print(f'{ch1} -> {ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f"{nll / n}")

. -> : 0.0000 -13.9506
 -> 阿: 1.0000 0.0000
阿 -> 安: 0.0010 -6.9217
安 -> .: 0.4295 -0.8452
. -> 阿: 0.0003 -7.9591
阿 -> 彬: 0.0020 -6.2285
彬 -> .: 0.9039 -0.1010
. -> 阿: 0.0003 -7.9591
阿 -> 斌: 0.0020 -6.2285
斌 -> .: 0.9176 -0.0860
. -> 阿: 0.0003 -7.9591
阿 -> 滨: 0.0010 -6.9217
滨 -> .: 0.9006 -0.1047
. -> 阿: 0.0003 -7.9591
阿 -> 冰: 0.0020 -6.2285
冰 -> .: 0.5933 -0.5221
. -> 阿: 0.0003 -7.9591
阿 -> 冰: 0.0020 -6.2285
冰 -> 冰: 0.0875 -2.4364
冰 -> .: 0.5933 -0.5221
. -> 阿: 0.0003 -7.9591
阿 -> 兵: 0.0010 -6.9217
兵 -> .: 0.9269 -0.0759
. -> 阿: 0.0003 -7.9591
阿 -> 婵: 0.0010 -6.9217
婵 -> .: 0.6959 -0.3626
. -> 阿: 0.0003 -7.9591
阿 -> 超: 0.0010 -6.9217
超 -> .: 0.7768 -0.2525
. -> 阿: 0.0003 -7.9591
阿 -> 朝: 0.0010 -6.9217
朝 -> .: 0.1668 -1.7912
log_likelihood=tensor(-159.1262)
nll=tensor(159.1262)
4.9726948738098145
