# 跟随 Andrej Karpathy 学习 Neural Networks: Zero to Hero 的笔记

In [2]:
words = open('./data/中文姓名集.txt', 'r').read().splitlines()

In [3]:
words[:10]

['\ufeff阿安', '阿彬', '阿斌', '阿滨', '阿冰', '阿冰冰', '阿兵', '阿婵', '阿超', '阿朝']

In [4]:
len(words)

1144629

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

3

In [7]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1



In [8]:
sorted(b.items(), key= lambda kv: -kv[1])


[(('<S>', '王'), 53987),
 (('<S>', '李'), 52439),
 (('<S>', '张'), 50448),
 (('<S>', '陈'), 44282),
 (('<S>', '刘'), 42847),
 (('<S>', '杨'), 28387),
 (('<S>', '黄'), 25987),
 (('<S>', '吴'), 25214),
 (('华', '<E>'), 23689),
 (('<S>', '周'), 21351),
 (('<S>', '赵'), 20651),
 (('<S>', '徐'), 19024),
 (('<S>', '朱'), 17343),
 (('明', '<E>'), 16987),
 (('<S>', '孙'), 16968),
 (('平', '<E>'), 16241),
 (('<S>', '林'), 16112),
 (('<S>', '胡'), 15493),
 (('<S>', '郭'), 14105),
 (('<S>', '郑'), 13661),
 (('林', '<E>'), 13619),
 (('<S>', '马'), 13431),
 (('军', '<E>'), 13093),
 (('<S>', '何'), 12908),
 (('英', '<E>'), 12889),
 (('文', '<E>'), 12651),
 (('<S>', '高'), 11178),
 (('芳', '<E>'), 11085),
 (('伟', '<E>'), 11062),
 (('<S>', '罗'), 10868),
 (('杰', '<E>'), 10775),
 (('龙', '<E>'), 10654),
 (('辉', '<E>'), 10442),
 (('红', '<E>'), 10408),
 (('生', '<E>'), 9929),
 (('强', '<E>'), 9740),
 (('<S>', '谢'), 9629),
 (('峰', '<E>'), 9567),
 (('<S>', '宋'), 9424),
 (('云', '<E>'), 9332),
 (('荣', '<E>'), 9244),
 (('梅', '<E>'), 9205),


In [9]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
N = torch.zeros((2272, 2272), dtype=torch.int32)


In [11]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

{'一': 1, '丁': 2, '七': 3, '万': 4, '三': 5, '上': 6, '不': 7, '与': 8, '专': 9, '丕': 10, '世': 11, '丘': 12, '丙': 13, '业': 14, '丛': 15, '东': 16, '丝': 17, '丞': 18, '严': 19, '丫': 20, '中': 21, '丰': 22, '临': 23, '丹': 24, '为': 25, '主': 26, '丽': 27, '举': 28, '乃': 29, '久': 30, '义': 31, '之': 32, '乌': 33, '乐': 34, '乔': 35, '乘': 36, '乙': 37, '九': 38, '也': 39, '习': 40, '乡': 41, '书': 42, '乾': 43, '予': 44, '争': 45, '事': 46, '二': 47, '于': 48, '云': 49, '亓': 50, '五': 51, '井': 52, '亚': 53, '亢': 54, '交': 55, '亦': 56, '产': 57, '亨': 58, '享': 59, '京': 60, '亭': 61, '亮': 62, '亲': 63, '人': 64, '亿': 65, '什': 66, '仁': 67, '仇': 68, '今': 69, '介': 70, '从': 71, '仑': 72, '仓': 73, '仔': 74, '仕': 75, '付': 76, '仙': 77, '仟': 78, '代': 79, '令': 80, '以': 81, '仪': 82, '仰': 83, '仲': 84, '任': 85, '仿': 86, '企': 87, '伊': 88, '伍': 89, '伏': 90, '休': 91, '众': 92, '优': 93, '伙': 94, '会': 95, '伟': 96, '传': 97, '伦': 98, '伯': 99, '伶': 100, '伸': 101, '伽': 102, '佃': 103, '但': 104, '位': 105, '住': 106, '佐': 107, '佑': 108, '体': 109, '何': 110, '佘': 11

In [12]:

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1


In [13]:
# plt.figure(figsize=(16, 16))
# plt.imshow(N, cmap='Blues')
# for i in range(2272):
#     for j in range(2272):
#         chstr = itos[i] + itos[j]
#         plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
#         plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
# plt.axis('off')

In [43]:
N[0, :].shape

torch.Size([2272])

In [44]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000e+00, 0.0000e+00, 5.2026e-03,  ..., 2.3003e-03, 2.5449e-03,
        8.7365e-07])

In [46]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'华'

In [36]:
# test 1
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [26]:
# test 2
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 2,
        2, 0, 0, 0])

In [55]:
p.shape

torch.Size([2272])

In [59]:
P.shape

torch.Size([2272, 2272])

In [70]:
P.sum(1)

tensor([1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000])

In [ ]:
# 2272 x 2272
# 2272 x 1

In [74]:
P = N.float()
P /= P.sum(1, keepdim=True)

In [77]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
    out = []
    ix = 0

    while True:
        # p = N[ix].float()
        # p = p / p.sum()
        # p = torch.ones(2272) / 2272
        p = P[ix]

        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

华.
张全庸.
林增源.
杨永策.
高宝.


In [ ]:
# log(a*b*c) = log(a) + log(b) + log(c)

In [87]:
log_likelihood = 0.0
for w in words[:10]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        print(f'{ch1} -> {ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')

. -> : 0.0000 -13.9506
 -> 阿: 1.0000 0.0000
阿 -> 安: 0.0010 -6.9217
安 -> .: 0.4295 -0.8452
. -> 阿: 0.0003 -7.9591
阿 -> 彬: 0.0020 -6.2285
彬 -> .: 0.9039 -0.1010
. -> 阿: 0.0003 -7.9591
阿 -> 斌: 0.0020 -6.2285
斌 -> .: 0.9176 -0.0860
. -> 阿: 0.0003 -7.9591
阿 -> 滨: 0.0010 -6.9217
滨 -> .: 0.9006 -0.1047
. -> 阿: 0.0003 -7.9591
阿 -> 冰: 0.0020 -6.2285
冰 -> .: 0.5933 -0.5221
. -> 阿: 0.0003 -7.9591
阿 -> 冰: 0.0020 -6.2285
冰 -> 冰: 0.0875 -2.4364
冰 -> .: 0.5933 -0.5221
. -> 阿: 0.0003 -7.9591
阿 -> 兵: 0.0010 -6.9217
兵 -> .: 0.9269 -0.0759
. -> 阿: 0.0003 -7.9591
阿 -> 婵: 0.0010 -6.9217
婵 -> .: 0.6959 -0.3626
. -> 阿: 0.0003 -7.9591
阿 -> 超: 0.0010 -6.9217
超 -> .: 0.7768 -0.2525
. -> 阿: 0.0003 -7.9591
阿 -> 朝: 0.0010 -6.9217
朝 -> .: 0.1668 -1.7912
log_likelihood=tensor(-159.1262)
